import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useRequisitions } from '../../../hooks/useRequisitions';
import { useAuth } from '../../../hooks/useAuth';
import { useNotifications } from '../../../hooks/useNotifications';
import LoadingSpinner from '../../common/LoadingSpinner/LoadingSpinner';
import Modal from '../../common/Modal/Modal';
import './RequisitionForm.css';

const RequisitionForm = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const isEdit = Boolean(id);
  
  const { 
    createRequisition, 
    updateRequisition, 
    getRequisition, 
    loading  } = useRequisitions();
  
  const { user } = useAuth();
  const { addNotification } = useNotifications();

  const [formData, setFormData] = useState({
    title: '',
    department: '',
    priority: 'medium',
    requiredDate: '',
    justification: '',
    items: [{ 
      productName: '', 
      description: '', 
      quantity: 1, 
      unit: 'pcs',
      estimatedCost: 0,
      catalogNumber: '',
      specifications: ''
    }],
    budgetCode: '',
    project: '',
    attachments: []
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  useEffect(() => {
    if (isEdit) {
      loadRequisition();
    } else {
      generateRequisitionNumber();
    }
  }, [id]);

  const loadRequisition = async () => {
    try {
      const requisition = await getRequisition(id);
      setFormData({
        title: requisition.title,
        department: requisition.department,
        priority: requisition.priority,
        requiredDate: requisition.requiredDate.split('T')[0],
        justification: requisition.justification,
        items: requisition.items,
        budgetCode: requisition.budgetCode || '',
        project: requisition.project || '',
        attachments: requisition.attachments || []
      });
    // eslint-disable-next-line no-unused-vars
    } catch (err) {
      addNotification('Failed to load requisition', 'error');
      navigate('/procurement/requisitions');
    }
  };

  const generateRequisitionNumber = () => {
    // This would typically be generated by the backend
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleItemChange = (index, field, value) => {
    const updatedItems = [...formData.items];
    updatedItems[index][field] = value;
    
    // Auto-calculate total if quantity or cost changes
    if (field === 'quantity' || field === 'estimatedCost') {
      updatedItems[index].total = updatedItems[index].quantity * updatedItems[index].estimatedCost;
    }
    
    setFormData(prev => ({ ...prev, items: updatedItems }));
  };

  const addItem = () => {
    setFormData(prev => ({
      ...prev,
      items: [...prev.items, { 
        productName: '', 
        description: '', 
        quantity: 1, 
        unit: 'pcs',
        estimatedCost: 0,
        catalogNumber: '',
        specifications: '',
        total: 0
      }]
    }));
  };

  const removeItem = (index) => {
    if (formData.items.length > 1) {
      const updatedItems = formData.items.filter((_, i) => i !== index);
      setFormData(prev => ({ ...prev, items: updatedItems }));
    }
  };

  const handleFileUpload = (e) => {
    const files = Array.from(e.target.files);
    setFormData(prev => ({
      ...prev,
      attachments: [...prev.attachments, ...files.map(file => ({
        name: file.name,
        size: file.size,
        type: file.type,
        file: file
      }))]
    }));
  };

  const removeAttachment = (index) => {
    setFormData(prev => ({
      ...prev,
      attachments: prev.attachments.filter((_, i) => i !== index)
    }));
  };

  const validateForm = () => {
    const errors = {};
    
    if (!formData.title.trim()) errors.title = 'Title is required';
    if (!formData.department.trim()) errors.department = 'Department is required';
    if (!formData.requiredDate) errors.requiredDate = 'Required date is required';
    if (!formData.justification.trim()) errors.justification = 'Justification is required';
    
    formData.items.forEach((item, index) => {
      if (!item.productName.trim()) errors[`item-${index}-name`] = `Item ${index + 1} name is required`;
      if (item.quantity <= 0) errors[`item-${index}-quantity`] = `Item ${index + 1} quantity must be greater than 0`;
      if (item.estimatedCost < 0) errors[`item-${index}-cost`] = `Item ${index + 1} cost cannot be negative`;
    });

    return errors;
  };

  const handleSubmit = async (e, status = 'submitted') => {
    e.preventDefault();
    
    const errors = validateForm();
    if (Object.keys(errors).length > 0) {
      addNotification('Please fix the form errors before submitting', 'error');
      return;
    }

    setIsSubmitting(true);
    
    try {
      const submissionData = {
        ...formData,
        status: status,
        requestedBy: {
          id: user.id,
          name: user.name,
          email: user.email,
          department: user.department
        },
        totalAmount: calculateTotalAmount()
      };

      if (isEdit) {
        await updateRequisition(id, submissionData);
        addNotification('Requisition updated successfully', 'success');
      } else {
        await createRequisition(submissionData);
        addNotification(`Requisition ${status === 'draft' ? 'saved as draft' : 'submitted successfully'}`, 'success');
      }
      navigate('/procurement/requisitions');
    // eslint-disable-next-line no-unused-vars
    } catch (err) {
      addNotification(`Failed to ${isEdit ? 'update' : 'create'} requisition`, 'error');
    } finally {
      setIsSubmitting(false);
    }
  };

  const calculateTotalAmount = () => {
    return formData.items.reduce((total, item) => total + (item.estimatedCost * item.quantity), 0);
  };

  const calculateItemTotal = (item) => {
    return item.quantity * item.estimatedCost;
  };

  const getPriorityColor = (priority) => {
    const colors = {
      low: '#28a745',
      medium: '#ffc107',
      high: '#fd7e14',
      urgent: '#dc3545'
    };
    return colors[priority];
  };

  if (loading) return <LoadingSpinner />;

  return (
    <div className="requisition-form">
      <div className="form-header">
        <h1>{isEdit ? 'Edit Requisition' : 'Create New Requisition'}</h1>
        <p>{isEdit ? 'Update your purchase requisition' : 'Create a new purchase requisition'}</p>
      </div>

      <form onSubmit={(e) => handleSubmit(e, 'submitted')} className="requisition-form-content">
        <div className="form-section">
          <h3>Basic Information</h3>
          <div className="form-grid">
            <div className="form-group">
              <label htmlFor="title">Requisition Title *</label>
              <input
                type="text"
                id="title"
                name="title"
                value={formData.title}
                onChange={handleInputChange}
                placeholder="Enter requisition title"
                required
              />
            </div>
            <div className="form-group">
              <label htmlFor="department">Department *</label>
              <select
                id="department"
                name="department"
                value={formData.department}
                onChange={handleInputChange}
                required
              >
                <option value="">Select Department</option>
                <option value="IT">IT Department</option>
                <option value="Finance">Finance</option>
                <option value="Operations">Operations</option>
                <option value="HR">Human Resources</option>
                <option value="Marketing">Marketing</option>
                <option value="Sales">Sales</option>
                <option value="Procurement">Procurement</option>
              </select>
            </div>
            <div className="form-group">
              <label htmlFor="priority">Priority *</label>
              <select
                id="priority"
                name="priority"
                value={formData.priority}
                onChange={handleInputChange}
                required
                style={{ borderLeft: `4px solid ${getPriorityColor(formData.priority)}` }}
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
            </div>
            <div className="form-group">
              <label htmlFor="requiredDate">Required Date *</label>
              <input
                type="date"
                id="requiredDate"
                name="requiredDate"
                value={formData.requiredDate}
                onChange={handleInputChange}
                min={new Date().toISOString().split('T')[0]}
                required
              />
            </div>
            <div className="form-group">
              <label htmlFor="budgetCode">Budget Code</label>
              <input
                type="text"
                id="budgetCode"
                name="budgetCode"
                value={formData.budgetCode}
                onChange={handleInputChange}
                placeholder="Enter budget code"
              />
            </div>
            <div className="form-group">
              <label htmlFor="project">Project</label>
              <input
                type="text"
                id="project"
                name="project"
                value={formData.project}
                onChange={handleInputChange}
                placeholder="Enter project name"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="justification">Justification *</label>
            <textarea
              id="justification"
              name="justification"
              value={formData.justification}
              onChange={handleInputChange}
              placeholder="Explain why this purchase is necessary..."
              rows="4"
              required
            />
          </div>
        </div>

        <div className="form-section">
          <div className="section-header">
            <h3>Items Required</h3>
            <div className="section-summary">
              <span>{formData.items.length} items</span>
              <span>Total: ${calculateTotalAmount().toLocaleString()}</span>
            </div>
          </div>
          
          <div className="items-list">
            {formData.items.map((item, index) => (
              <div key={index} className="item-card">
                <div className="item-header">
                  <h4>Item {index + 1}</h4>
                  <button
                    type="button"
                    className="btn btn--danger btn--sm"
                    onClick={() => removeItem(index)}
                    disabled={formData.items.length === 1}
                  >
                    Remove
                  </button>
                </div>
                
                <div className="item-grid">
                  <div className="form-group">
                    <label>Product Name *</label>
                    <input
                      type="text"
                      value={item.productName}
                      onChange={(e) => handleItemChange(index, 'productName', e.target.value)}
                      placeholder="Enter product name"
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Catalog Number</label>
                    <input
                      type="text"
                      value={item.catalogNumber}
                      onChange={(e) => handleItemChange(index, 'catalogNumber', e.target.value)}
                      placeholder="Catalog/SKU number"
                    />
                  </div>
                  <div className="form-group">
                    <label>Description</label>
                    <input
                      type="text"
                      value={item.description}
                      onChange={(e) => handleItemChange(index, 'description', e.target.value)}
                      placeholder="Product description"
                    />
                  </div>
                  <div className="form-group">
                    <label>Specifications</label>
                    <input
                      type="text"
                      value={item.specifications}
                      onChange={(e) => handleItemChange(index, 'specifications', e.target.value)}
                      placeholder="Technical specifications"
                    />
                  </div>
                  <div className="form-group">
                    <label>Quantity *</label>
                    <input
                      type="number"
                      value={item.quantity}
                      onChange={(e) => handleItemChange(index, 'quantity', parseInt(e.target.value) || 0)}
                      min="1"
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Unit</label>
                    <select
                      value={item.unit}
                      onChange={(e) => handleItemChange(index, 'unit', e.target.value)}
                    >
                      <option value="pcs">Pieces</option>
                      <option value="kg">Kilograms</option>
                      <option value="liters">Liters</option>
                      <option value="meters">Meters</option>
                      <option value="boxes">Boxes</option>
                      <option value="units">Units</option>
                      <option value="sets">Sets</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Estimated Cost ($) *</label>
                    <input
                      type="number"
                      step="0.01"
                      value={item.estimatedCost}
                      onChange={(e) => handleItemChange(index, 'estimatedCost', parseFloat(e.target.value) || 0)}
                      min="0"
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label>Total</label>
                    <div className="item-total">
                      ${calculateItemTotal(item).toLocaleString()}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          <button
            type="button"
            className="btn btn--outline"
            onClick={addItem}
          >
            + Add Another Item
          </button>
        </div>

        <div className="form-section">
          <h3>Attachments</h3>
          <div className="attachments-section">
            <div className="file-upload">
              <input
                type="file"
                id="attachments"
                multiple
                onChange={handleFileUpload}
                className="file-input"
              />
              <label htmlFor="attachments" className="btn btn--outline">
                Choose Files
              </label>
              <span>Supporting documents, quotes, specifications</span>
            </div>
            
            {formData.attachments.length > 0 && (
              <div className="attachments-list">
                <h4>Attached Files:</h4>
                {formData.attachments.map((file, index) => (
                  <div key={index} className="attachment-item">
                    <span className="file-name">{file.name}</span>
                    <span className="file-size">({(file.size / 1024).toFixed(1)} KB)</span>
                    <button
                      type="button"
                      className="btn btn--danger btn--sm"
                      onClick={() => removeAttachment(index)}
                    >
                      Remove
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="form-actions">
          <div className="action-left">
            <button
              type="button"
              className="btn btn--secondary"
              onClick={() => navigate('/procurement/requisitions')}
            >
              Cancel
            </button>
            <button
              type="button"
              className="btn btn--outline"
              onClick={(e) => handleSubmit(e, 'draft')}
              disabled={isSubmitting}
            >
              Save as Draft
            </button>
          </div>
          <div className="action-right">
            <button
              type="button"
              className="btn btn--info"
              onClick={() => setShowPreview(true)}
            >
              Preview
            </button>
            <button
              type="submit"
              className="btn btn--primary"
              disabled={isSubmitting}
            >
              {isSubmitting ? 'Submitting...' : 'Submit Requisition'}
            </button>
          </div>
        </div>
      </form>

      {/* Preview Modal */}
      <Modal
        isOpen={showPreview}
        onClose={() => setShowPreview(false)}
        title="Requisition Preview"
        size="large"
      >
        <div className="requisition-preview">
          <div className="preview-header">
            <h2>{formData.title}</h2>
            <div className="preview-meta">
              <span className={`priority-badge priority-badge--${formData.priority}`}>
                {formData.priority}
              </span>
              <span>Department: {formData.department}</span>
            </div>
          </div>
          
          <div className="preview-section">
            <h4>Items</h4>
            <table className="preview-table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th>Description</th>
                  <th>Qty</th>
                  <th>Unit</th>
                  <th>Est. Cost</th>
                  <th>Total</th>
                </tr>
              </thead>
              <tbody>
                {formData.items.map((item, index) => (
                  <tr key={index}>
                    <td>{item.productName}</td>
                    <td>{item.description}</td>
                    <td>{item.quantity}</td>
                    <td>{item.unit}</td>
                    <td>${item.estimatedCost.toLocaleString()}</td>
                    <td>${calculateItemTotal(item).toLocaleString()}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr>
                  <td colSpan="5" style={{ textAlign: 'right', fontWeight: 'bold' }}>Grand Total:</td>
                  <td style={{ fontWeight: 'bold' }}>${calculateTotalAmount().toLocaleString()}</td>
                </tr>
              </tfoot>
            </table>
          </div>
          
          <div className="preview-section">
            <h4>Justification</h4>
            <p>{formData.justification}</p>
          </div>
          
          <div className="modal-actions">
            <button 
              className="btn btn--secondary"
              onClick={() => setShowPreview(false)}
            >
              Close Preview
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};

export default RequisitionForm;