export const SUPPLIER_CATEGORIES = {
  RAW_MATERIALS: 'raw_materials',
  MANUFACTURING: 'manufacturing',
  SERVICES: 'services',
  TECHNOLOGY: 'technology',
  LOGISTICS: 'logistics',
  CONSULTING: 'consulting',
  MAINTENANCE: 'maintenance',
  OFFICE_SUPPLIES: 'office_supplies',
  CONSTRUCTION: 'construction',
  HEALTHCARE: 'healthcare',
  FOOD_BEVERAGE: 'food_beverage',
  RETAIL: 'retail',
  OTHER: 'other'
};

export const SUPPLIER_CATEGORY_LABELS = {
  [SUPPLIER_CATEGORIES.RAW_MATERIALS]: 'Raw Materials',
  [SUPPLIER_CATEGORIES.MANUFACTURING]: 'Manufacturing',
  [SUPPLIER_CATEGORIES.SERVICES]: 'Services',
  [SUPPLIER_CATEGORIES.TECHNOLOGY]: 'Technology',
  [SUPPLIER_CATEGORIES.LOGISTICS]: 'Logistics & Transportation',
  [SUPPLIER_CATEGORIES.CONSULTING]: 'Consulting',
  [SUPPLIER_CATEGORIES.MAINTENANCE]: 'Maintenance & Repair',
  [SUPPLIER_CATEGORIES.OFFICE_SUPPLIES]: 'Office Supplies',
  [SUPPLIER_CATEGORIES.CONSTRUCTION]: 'Construction',
  [SUPPLIER_CATEGORIES.HEALTHCARE]: 'Healthcare',
  [SUPPLIER_CATEGORIES.FOOD_BEVERAGE]: 'Food & Beverage',
  [SUPPLIER_CATEGORIES.RETAIL]: 'Retail',
  [SUPPLIER_CATEGORIES.OTHER]: 'Other'
};

export const SUPPLIER_CATEGORY_ICONS = {
  [SUPPLIER_CATEGORIES.RAW_MATERIALS]: '🏭',
  [SUPPLIER_CATEGORIES.MANUFACTURING]: '⚙️',
  [SUPPLIER_CATEGORIES.SERVICES]: '🔧',
  [SUPPLIER_CATEGORIES.TECHNOLOGY]: '💻',
  [SUPPLIER_CATEGORIES.LOGISTICS]: '🚚',
  [SUPPLIER_CATEGORIES.CONSULTING]: '📊',
  [SUPPLIER_CATEGORIES.MAINTENANCE]: '🛠️',
  [SUPPLIER_CATEGORIES.OFFICE_SUPPLIES]: '📎',
  [SUPPLIER_CATEGORIES.CONSTRUCTION]: '🏗️',
  [SUPPLIER_CATEGORIES.HEALTHCARE]: '🏥',
  [SUPPLIER_CATEGORIES.FOOD_BEVERAGE]: '🍎',
  [SUPPLIER_CATEGORIES.RETAIL]: '🛒',
  [SUPPLIER_CATEGORIES.OTHER]: '📦'
};

export default SUPPLIER_CATEGORIES;